ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,7 +16,6 @@ env:
   PYRDL_REPO: https://github.com/DanaResearchGroup/RingDecomposerLib
 
 jobs:
-
   setup:
     name: Setup Environments and Dependencies
     runs-on: ubuntu-latest
@@ -56,14 +55,7 @@ jobs:
           git clone -b setup3 $PYRDL_REPO RingDecomposerLib &
           wait
 
-      - name: Install PyRDL into arc_env
-        run: |
-          echo ">>> Installing PyRDL into arc_env…"
-          cd RingDecomposerLib/src/python
-          micromamba run -n arc_env pip install --no-build-isolation .
-          micromamba run -n arc_env pip show py_rdl
-
-      - name: Install other external tools
+      - name: Install all external tools
         working-directory: ARC
         run: |
           DEBUG_INSTALL=1 micromamba run -n arc_env make install-all
@@ -82,8 +74,8 @@ jobs:
 
   unit-test:
     name: Run Unit Tests
-    runs-on: ubuntu-latest
     needs: setup
+    runs-on: ubuntu-latest
     defaults:
       run:
         shell: bash -el {0}
@@ -107,17 +99,15 @@ jobs:
           create-args: --strict-channel-priority
           generate-run-shell: true
 
-      - name: Sanity-check PyRDL installation
+      - name: Sanity check PyRDL in arc_env
         run: |
-          micromamba run -n arc_env pip show py_rdl || {
-            echo "❌ py_rdl not found in arc_env"; exit 1;
-          }
+          micromamba run -n arc_env pip show py_rdl || \
+            (echo "❌ py_rdl missing from arc_env" && exit 1)
 
       - name: Run Unit Tests
         working-directory: ARC
         run: |
           micromamba run -n arc_env bash -lc "
-            # Only add the other repos to PYTHONPATH; py_rdl lives in site-packages
             export PYTHONPATH=\"\$PWD/../molecule:\$PWD/../AutoTST:\$PWD/../RMG-database:\$PWD/../KinBot\"
             make test
           "
@@ -130,8 +120,8 @@ jobs:
 
   functional-test:
     name: Run Functional Tests
-    runs-on: ubuntu-latest
     needs: setup
+    runs-on: ubuntu-latest
     defaults:
       run:
         shell: bash -el {0}
@@ -165,8 +155,8 @@ jobs:
 
   codecov:
     name: Upload Code Coverage
-    runs-on: ubuntu-latest
     needs: unit-test
+    runs-on: ubuntu-latest
 
     steps:
       - name: Download coverage data
@@ -181,6 +171,4 @@ jobs:
           token: ${{ secrets.CODECOV_TOKEN }}
           file: coverage.xml
           flags: unittests
-          name: codecov-umbrella
-          verbose: true
           fail_ci_if_error: false
